# Generated by Django 4.0.2 on 2022-03-07 13:06

import about_me.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=about_me.models.upload_news_image_path)),
                ('description', models.TextField()),
                ('years_of_experience', models.SmallIntegerField()),
                ('projects_completed', models.SmallIntegerField()),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
            ],
        ),
    ]
