# Generated by Django 4.0.2 on 2022-03-08 06:02

import about_me.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(upload_to=about_me.models.upload_about_me_image_path),
        ),
    ]
