# Generated by Django 4.0.2 on 2022-03-08 06:02

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=project.models.upload_project_image_path),
        ),
    ]
